plugins {
    id 'java'
    id 'war'
}

group = 'src.islab1jee'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation platform("jakarta.platform:jakarta.jakartaee-bom:11.0.0")
    providedCompile "jakarta.platform:jakarta.jakartaee-api:11.0.0"
    implementation "org.hibernate.orm:hibernate-core:6.6.1.Final"
    implementation 'org.postgresql:postgresql:42.7.7'
    implementation 'jakarta.persistence:jakarta.persistence-api:3.1.0'
    compileOnly "org.projectlombok:lombok:1.18.34"
    annotationProcessor "org.projectlombok:lombok:1.18.34"
    testImplementation "org.junit.jupiter:junit-jupiter:5.11.3"
}

tasks.test {
    useJUnitPlatform()
}
