db.url=jdbc:postgresql://localhost:5432/studs
db.username=s408145
db.password=JLzD%6772
db.driver=org.postgresql.Driver

db.minIdle=5
db.maxIdle=10
db.maxTotal=20
db.maxWaitMillis=10000
db.validationQuery=SELECT 1
db.testOnBorrow=true
